version: '0.1.1-{build}'

os: Visual Studio 2015

environment:
  matrix:
    # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
      arch: x86_64
      mingw_dir: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu
      arch: x86
      mingw_dir: C:\Qt\Tools\mingw730_32\bin

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%mingw_dir%;%PATH%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

before_build:
  - git submodule update --init --recursive

build_script:
  - cd librespot
  - cargo build --release

artifacts:
  - path: librespot\target\release\librespot.exe
    name: librespot-%arch%
